name: PSGallery
on:
  release:
    types: [published]
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        run: |
          Publish-Module -Path 'psDevOpsTool' -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh